### PR TITLE
#1 re-write queries & related code refactor

### PR DESCRIPTION
**Pull request by thomasmodeneis**
#1 - re-write queries & related code refactor
#1 add read_mode option, cleanup indexes, add action index for recent_recommendations_by_people

### CODE REVIEW

**Comment by thomasmodeneis** [comment]
Fixes #6

**Comment by thomasmodeneis** [comment]
@grahamjenson I noticed CI job is failing with `No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)`, Do you know what is wrong there ?

**Comment by thomasmodeneis** [comment]
If you can please also release the NPM module with the new version ? 
Cheers.

**Comment by grahamjenson** [comment]
I have released a new version on npm.

**Pull request merged**
